[package]
name = "onlyargs_derive-app"
description = "Example app for onlyargs_derive"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "onlyargs_derive-app"
path = "app.rs"

[dependencies]
onlyargs = "0.1"
onlyargs_derive = "0.1"
